name: longdo_maps_api3_flutter
description: "Flutter plugin for integrating Longdo Maps in iOS and Android applications."
version: 1.3.0
homepage: "https://map.longdo.com/products"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.longdo.map.api3.longdo_maps_api3_flutter
        pluginClass: LongdoMapsApi3FlutterPlugin
      ios:
        pluginClass: LongdoMapsApi3FlutterPlugin
  assets:
    - index.html